export const SERVER_ACTION_TYPES = {
    SET_SETTING: 'SET_SETTING',
    START_GAME: 'START_GAME',
    MOVE_PLAYER: 'MOVE_PLAYER',
    NEXT_GAME: 'NEXT_GAME',
    BACK_TO_SETTINGS: 'BACK_TO_SETTINGS'
}